-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgdNKknJTtoHbM1h5e
nyC8SUrIOSufkJIHbYmpUSsqdHKgCgYIKoZIzj0DAQehRANCAAQj2tg4sYU3y8fp
SL7dmKmADN7VnkEtlQfEPXgRGcwhtfdlE5YTSCO5R2DtzDQyVsKmzBkhT8QlVyaT
Ndp+IUIk
-----END PRIVATE KEY-----